ChannelSettings:
  description: Base channel settings. Only the channel settings corresponding to the channel specified in the channelType field is or should be present.
  discriminator: channelType
  required:
    - channelType
    - direction
  properties:
    channelType:
      description: Channel type code
      type: string
    direction:
      description: 0 for Rx only, 1 for Tx only or 2 for any number and direction (default 0)
      type: integer
      minimum: 0
      maximum: 2
    originatorDeviceSetIndex:
      description: Optional for reverse API. This is the device set index from where the message comes from.
      type: integer
    originatorChannelIndex:
      description: Optional for reverse API. This is the channel index from where the message comes from.
      type: integer
    ADSBDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/ADSBDemod.yaml#/ADSBDemodSettings"
      description: "ADS-B demod settings configuration for Channel."
    AISDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/AISDemod.yaml#/AISDemodSettings"
      description: "AIS demod settings configuration for Channel."
    AISModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/AISMod.yaml#/AISModSettings"
      description: "AIS mod settings configuration for Channel."
    AMDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/AMDemod.yaml#/AMDemodSettings"
      description: "Am demod settings configuration for Channel."
    AMModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/AMMod.yaml#/AMModSettings"
      description: "Am mod settings configuration for Channel."
    APTDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/APTDemod.yaml#/APTDemodSettings"
      description: "Apt demod settings configuration for Channel."
    ATVDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/ATVDemod.yaml#/ATVDemodSettings"
      description: "Atv demod settings configuration for Channel."
    ATVModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/ATVMod.yaml#/ATVModSettings"
      description: "Atv mod settings configuration for Channel."
    BeamSteeringCWModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/BeamSteeringCWMod.yaml#/BeamSteeringCWModSettings"
      description: "Beam steering CW mod settings configuration for Channel."
    BFMDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/BFMDemod.yaml#/BFMDemodSettings"
      description: "BFM demod settings configuration for Channel."
    ChannelAnalyzerSettings:
      $ref: "http://swgserver:8081/api/swagger/include/ChannelAnalyzer.yaml#/ChannelAnalyzerSettings"
      description: "Channel analyzer settings configuration for Channel."
    ChannelPowerSettings:
      $ref: "http://swgserver:8081/api/swagger/include/ChannelPower.yaml#/ChannelPowerSettings"
      description: "Channel power settings configuration for Channel."
    ChirpChatDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/ChirpChatDemod.yaml#/ChirpChatDemodSettings"
      description: "Chirp chat demod settings configuration for Channel."
    ChirpChatModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/ChirpChatMod.yaml#/ChirpChatModSettings"
      description: "Chirp chat mod settings configuration for Channel."
    DATVModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/DATVMod.yaml#/DATVModSettings"
      description: "Datv mod settings configuration for Channel."
    DATVDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/DATVDemod.yaml#/DATVDemodSettings"
      description: "Datv demod settings configuration for Channel."
    DABDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/DABDemod.yaml#/DABDemodSettings"
      description: "Dab demod settings configuration for Channel."
    DOA2Settings:
      $ref: "http://swgserver:8081/api/swagger/include/DOA2.yaml#/DOA2Settings"
      description: "Doa2 settings configuration for Channel."
    DSCDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/DSCDemod.yaml#/DSCDemodSettings"
      description: "Dsc demod settings configuration for Channel."
    DSDDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/DSDDemod.yaml#/DSDDemodSettings"
      description: "Dsd demod settings configuration for Channel."
    EndOfTrainDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/EndOfTrainDemod.yaml#/EndOfTrainDemodSettings"
      description: "End of train demod settings configuration for Channel."
    FileSinkSettings:
      $ref: "http://swgserver:8081/api/swagger/include/FileSink.yaml#/FileSinkSettings"
      description: "File sink settings configuration for Channel."
    FileSourceSettings:
      $ref: "http://swgserver:8081/api/swagger/include/FileSource.yaml#/FileSourceSettings"
      description: "File source settings configuration for Channel."
    FreeDVDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/FreeDVDemod.yaml#/FreeDVDemodSettings"
      description: "Free dv demod settings configuration for Channel."
    FreeDVModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/FreeDVMod.yaml#/FreeDVModSettings"
      description: "Free dv mod settings configuration for Channel."
    FreqScannerSettings:
      $ref: "http://swgserver:8081/api/swagger/include/FreqScanner.yaml#/FreqScannerSettings"
      description: "Freq scanner settings configuration for Channel."
    FreqTrackerSettings:
      $ref: "http://swgserver:8081/api/swagger/include/FreqTracker.yaml#/FreqTrackerSettings"
      description: "Freq tracker settings configuration for Channel."
    FT8DemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/FT8Demod.yaml#/FT8DemodSettings"
      description: "Ft8 demod settings configuration for Channel."
    HeatMapSettings:
      $ref: "http://swgserver:8081/api/swagger/include/HeatMap.yaml#/HeatMapSettings"
      description: "Heat map settings configuration for Channel."
    ILSDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/ILSDemod.yaml#/ILSDemodSettings"
      description: "Ils demod settings configuration for Channel."
    InmarsatDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/InmarsatDemod.yaml#/InmarsatDemodSettings"
      description: "Inmarsat demod settings configuration for Channel."
    InterferometerSettings:
      $ref: "http://swgserver:8081/api/swagger/include/Interferometer.yaml#/InterferometerSettings"
      description: "Interferometer settings configuration for Channel."
    IEEE_802_15_4_ModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/IEEE_802_15_4_Mod.yaml#/IEEE_802_15_4_ModSettings"
      description: "Ieee 802 15 4 mod settings configuration for Channel."
    M17DemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/M17Demod.yaml#/M17DemodSettings"
      description: "M17 demod settings configuration for Channel."
    M17ModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/M17Mod.yaml#/M17ModSettings"
      description: "M17 mod settings configuration for Channel."
    MeshtasticDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/MeshtasticDemod.yaml#/MeshtasticDemodSettings"
      description: "Meshtastic demod settings configuration for Channel."
    MeshtasticModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/MeshtasticMod.yaml#/MeshtasticModSettings"
      description: "Meshtastic mod settings configuration for Channel."
    MeshcoreDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/MeshcoreDemod.yaml#/MeshcoreDemodSettings"
      description: "Meshcore demod settings configuration for Channel."
    MeshcoreModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/MeshcoreMod.yaml#/MeshcoreModSettings"
      description: "Meshcore mod settings configuration for Channel."
    NavtexDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/NavtexDemod.yaml#/NavtexDemodSettings"
      description: "Navtex demod settings configuration for Channel."
    NFMDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/NFMDemod.yaml#/NFMDemodSettings"
      description: "Nfm demod settings configuration for Channel."
    NFMModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/NFMMod.yaml#/NFMModSettings"
      description: "Nfm mod settings configuration for Channel."
    NoiseFigureSettings:
      $ref: "http://swgserver:8081/api/swagger/include/NoiseFigure.yaml#/NoiseFigureSettings"
      description: "Noise figure settings configuration for Channel."
    LocalSinkSettings:
      $ref: "http://swgserver:8081/api/swagger/include/LocalSink.yaml#/LocalSinkSettings"
      description: "Local sink settings configuration for Channel."
    LocalSourceSettings:
      $ref: "http://swgserver:8081/api/swagger/include/LocalSource.yaml#/LocalSourceSettings"
      description: "Local source settings configuration for Channel."
    PacketDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/PacketDemod.yaml#/PacketDemodSettings"
      description: "Packet demod settings configuration for Channel."
    PacketModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/PacketMod.yaml#/PacketModSettings"
      description: "Packet mod settings configuration for Channel."
    PagerDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/PagerDemod.yaml#/PagerDemodSettings"
      description: "Pager demod settings configuration for Channel."
    PSK31ModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/PSK31Mod.yaml#/PSK31ModSettings"
      description: "Psk31 mod settings configuration for Channel."
    RadioAstronomySettings:
      $ref: "http://swgserver:8081/api/swagger/include/RadioAstronomy.yaml#/RadioAstronomySettings"
      description: "Radio astronomy settings configuration for Channel."
    RadioClockSettings:
      $ref: "http://swgserver:8081/api/swagger/include/RadioClock.yaml#/RadioClockSettings"
      description: "Radio clock settings configuration for Channel."
    RadiosondeDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/RadiosondeDemod.yaml#/RadiosondeDemodSettings"
      description: "Radiosonde demod settings configuration for Channel."
    RemoteSinkSettings:
      $ref: "http://swgserver:8081/api/swagger/include/RemoteSink.yaml#/RemoteSinkSettings"
      description: "Remote sink settings configuration for Channel."
    RemoteSourceSettings:
      $ref: "http://swgserver:8081/api/swagger/include/RemoteSource.yaml#/RemoteSourceSettings"
      description: "Remote source settings configuration for Channel."
    RemoteTCPSinkSettings:
      $ref: "http://swgserver:8081/api/swagger/include/RemoteTCPSink.yaml#/RemoteTCPSinkSettings"
      description: "Remote TCP sink settings configuration for Channel."
    RTTYDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/RTTYDemod.yaml#/RTTYDemodSettings"
      description: "Rtty demod settings configuration for Channel."
    RTTYModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/RTTYMod.yaml#/RTTYModSettings"
      description: "Rtty mod settings configuration for Channel."
    SigMFFileSinkSettings:
      $ref: "http://swgserver:8081/api/swagger/include/SigMFFileSink.yaml#/SigMFFileSinkSettings"
      description: "Sig mf file sink settings configuration for Channel."
    SSBModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/SSBMod.yaml#/SSBModSettings"
      description: "Ssb mod settings configuration for Channel."
    SSBDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/SSBDemod.yaml#/SSBDemodSettings"
      description: "Ssb demod settings configuration for Channel."
    UDPSourceSettings:
      $ref: "http://swgserver:8081/api/swagger/include/UDPSource.yaml#/UDPSourceSettings"
      description: "UDP source settings configuration for Channel."
    UDPSinkSettings:
      $ref: "http://swgserver:8081/api/swagger/include/UDPSink.yaml#/UDPSinkSettings"
      description: "UDP sink settings configuration for Channel."
    # VORDemodMCSettings:
    #   $ref: "http://swgserver:8081/api/swagger/include/VORDemodMC.yaml#/VORDemodMCSettings"
    VORDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/VORDemod.yaml#/VORDemodSettings"
      description: "Vor demod settings configuration for Channel."
    WDSPRxSettings:
      $ref: "http://swgserver:8081/api/swagger/include/WDSPRx.yaml#/WDSPRxSettings"
      description: "Wdsp receive settings configuration for Channel."
    WFMDemodSettings:
      $ref: "http://swgserver:8081/api/swagger/include/WFMDemod.yaml#/WFMDemodSettings"
      description: "Wfm demod settings configuration for Channel."
    WFMModSettings:
      $ref: "http://swgserver:8081/api/swagger/include/WFMMod.yaml#/WFMModSettings"
      description: "Wfm mod settings configuration for Channel."
