#ifndef VERSION_H__
#define VERSION_H__

#define LIBBLADERF_VERSION       "1.6.1-git-unknown"

#define LIBBLADERF_VERSION_MAJOR 1
#define LIBBLADERF_VERSION_MINOR 6
#define LIBBLADERF_VERSION_PATCH 1

#endif
