#ifndef VERSION_H__
#define VERSION_H__

#define LIBBLADERF_VERSION       "1.9.0-git-23c6379e"

#define LIBBLADERF_VERSION_MAJOR 1
#define LIBBLADERF_VERSION_MINOR 7
#define LIBBLADERF_VERSION_PATCH 2

#endif
