Document: sdrangel
Title: Debian sdrangel Manual
Author: <insert document author here>
Abstract: This manual describes what sdrangel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sdrangel/sdrangel.sgml.gz

Format: postscript
Files: /usr/share/doc/sdrangel/sdrangel.ps.gz

Format: text
Files: /usr/share/doc/sdrangel/sdrangel.text.gz

Format: HTML
Index: /usr/share/doc/sdrangel/html/index.html
Files: /usr/share/doc/sdrangel/html/*.html
