/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGBFMModSettings.h
 *
 * BFMMod
 */

#ifndef SWGBFMModSettings_H_
#define SWGBFMModSettings_H_

#include <QJsonObject>


#include "SWGCWKeyerSettings.h"
#include "SWGChannelMarker.h"
#include "SWGRollupState.h"
#include <QString>

#include "SWGObject.h"
#include "export.h"

namespace SWGSDRangel {

class SWG_API SWGBFMModSettings: public SWGObject {
public:
    SWGBFMModSettings();
    SWGBFMModSettings(QString* json);
    virtual ~SWGBFMModSettings();
    void init();
    void cleanup();

    virtual QString asJson () override;
    virtual QJsonObject* asJsonObject() override;
    virtual void fromJsonObject(QJsonObject &json) override;
    virtual SWGBFMModSettings* fromJson(QString &jsonString) override;

    qint64 getInputFrequencyOffset();
    void setInputFrequencyOffset(qint64 input_frequency_offset);

    float getRfBandwidth();
    void setRfBandwidth(float rf_bandwidth);

    float getAfBandwidth();
    void setAfBandwidth(float af_bandwidth);

    float getFmDeviation();
    void setFmDeviation(float fm_deviation);

    float getToneFrequency();
    void setToneFrequency(float tone_frequency);

    float getVolumeFactor();
    void setVolumeFactor(float volume_factor);

    qint32 getAudioStereo();
    void setAudioStereo(qint32 audio_stereo);

    qint32 getPreEmphasis();
    void setPreEmphasis(qint32 pre_emphasis);

    float getPilotLevel();
    void setPilotLevel(float pilot_level);

    qint32 getRdsActive();
    void setRdsActive(qint32 rds_active);

    float getRdsLevel();
    void setRdsLevel(float rds_level);

    qint32 getRdsPi();
    void setRdsPi(qint32 rds_pi);

    qint32 getRdsPty();
    void setRdsPty(qint32 rds_pty);

    QString* getRdsPs();
    void setRdsPs(QString* rds_ps);

    QString* getRdsRadioText();
    void setRdsRadioText(QString* rds_radio_text);

    qint32 getChannelMute();
    void setChannelMute(qint32 channel_mute);

    qint32 getPlayLoop();
    void setPlayLoop(qint32 play_loop);

    qint32 getRgbColor();
    void setRgbColor(qint32 rgb_color);

    QString* getTitle();
    void setTitle(QString* title);

    QString* getAudioDeviceName();
    void setAudioDeviceName(QString* audio_device_name);

    QString* getFeedbackAudioDeviceName();
    void setFeedbackAudioDeviceName(QString* feedback_audio_device_name);

    float getFeedbackVolumeFactor();
    void setFeedbackVolumeFactor(float feedback_volume_factor);

    qint32 getFeedbackAudioEnable();
    void setFeedbackAudioEnable(qint32 feedback_audio_enable);

    QString* getFileName();
    void setFileName(QString* file_name);

    qint32 getModAfInput();
    void setModAfInput(qint32 mod_af_input);

    qint32 getStreamIndex();
    void setStreamIndex(qint32 stream_index);

    qint32 getUseReverseApi();
    void setUseReverseApi(qint32 use_reverse_api);

    QString* getReverseApiAddress();
    void setReverseApiAddress(QString* reverse_api_address);

    qint32 getReverseApiPort();
    void setReverseApiPort(qint32 reverse_api_port);

    qint32 getReverseApiDeviceIndex();
    void setReverseApiDeviceIndex(qint32 reverse_api_device_index);

    qint32 getReverseApiChannelIndex();
    void setReverseApiChannelIndex(qint32 reverse_api_channel_index);

    SWGCWKeyerSettings* getCwKeyer();
    void setCwKeyer(SWGCWKeyerSettings* cw_keyer);

    SWGChannelMarker* getChannelMarker();
    void setChannelMarker(SWGChannelMarker* channel_marker);

    SWGRollupState* getRollupState();
    void setRollupState(SWGRollupState* rollup_state);


    virtual bool isSet() override;

private:
    qint64 input_frequency_offset;
    bool m_input_frequency_offset_isSet;

    float rf_bandwidth;
    bool m_rf_bandwidth_isSet;

    float af_bandwidth;
    bool m_af_bandwidth_isSet;

    float fm_deviation;
    bool m_fm_deviation_isSet;

    float tone_frequency;
    bool m_tone_frequency_isSet;

    float volume_factor;
    bool m_volume_factor_isSet;

    qint32 audio_stereo;
    bool m_audio_stereo_isSet;
    qint32 pre_emphasis;
    bool m_pre_emphasis_isSet;
    float pilot_level;
    bool m_pilot_level_isSet;
    qint32 rds_active;
    bool m_rds_active_isSet;
    float rds_level;
    bool m_rds_level_isSet;
    qint32 rds_pi;
    bool m_rds_pi_isSet;
    qint32 rds_pty;
    bool m_rds_pty_isSet;
    QString* rds_ps;
    bool m_rds_ps_isSet;
    QString* rds_radio_text;
    bool m_rds_radio_text_isSet;

    qint32 channel_mute;
    bool m_channel_mute_isSet;

    qint32 play_loop;
    bool m_play_loop_isSet;

    qint32 rgb_color;
    bool m_rgb_color_isSet;

    QString* title;
    bool m_title_isSet;

    QString* audio_device_name;
    bool m_audio_device_name_isSet;

    QString* feedback_audio_device_name;
    bool m_feedback_audio_device_name_isSet;

    float feedback_volume_factor;
    bool m_feedback_volume_factor_isSet;

    qint32 feedback_audio_enable;
    bool m_feedback_audio_enable_isSet;

    QString* file_name;
    bool m_file_name_isSet;

    qint32 mod_af_input;
    bool m_mod_af_input_isSet;

    qint32 stream_index;
    bool m_stream_index_isSet;

    qint32 use_reverse_api;
    bool m_use_reverse_api_isSet;

    QString* reverse_api_address;
    bool m_reverse_api_address_isSet;

    qint32 reverse_api_port;
    bool m_reverse_api_port_isSet;

    qint32 reverse_api_device_index;
    bool m_reverse_api_device_index_isSet;

    qint32 reverse_api_channel_index;
    bool m_reverse_api_channel_index_isSet;

    SWGCWKeyerSettings* cw_keyer;
    bool m_cw_keyer_isSet;

    SWGChannelMarker* channel_marker;
    bool m_channel_marker_isSet;

    SWGRollupState* rollup_state;
    bool m_rollup_state_isSet;

};

}

#endif /* SWGBFMModSettings_H_ */
