# Find Lime Suite

FIND_PATH(LIMESUITE_INCLUDE_DIR lime/LimeSuite.h)

IF (LIMESUITE_INCLUDE_DIR AND LIMESUITE_LIBRARY)
    SET(LIMESUITE_FOUND TRUE)
ENDIF (LIMESUITE_INCLUDE_DIR AND LIMESUITE_LIBRARY)

IF (LIMESUITE_FOUND)
    MESSAGE (STATUS "Found Lime Suite: ${LIMESUITE_INCLUDE_DIR}, ${LIMESUITE_LIBRARY}")
ELSE (LIMESUITE_FOUND)
    MESSAGE (STATUS "Could not find Lime Suite")
ENDIF (LIMESUITE_FOUND)

mark_as_advanced(LIMESUITE_INCLUDE_DIR LIMESUITE_LIBRARY)
