name: SDRangel Linux Coverity build

# Run every day at 3:00am UTC
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build_coverity:
    if: github.repository == 'f4exb/sdrangel'
    # run once on latest
    runs-on: ubuntu-24.04
    env:
      COVERITY_SCAN_PROJECT_NAME: ${{ github.repository }}
      COVERITY_SCAN_PROJECT_ID : "33161"
      COVERITY_SCAN_NOTIFICATION_EMAIL: ${{ secrets.COVERITY_SCAN_NOTIFICATION_EMAIL }}
      COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Check Coverity
        id: coverity_check
        run: |
          ./.github/workflows/coverity.sh --precheck
      # keep dependencies synced with linux.yml
      - name: Install dependencies
        if: steps.coverity_check.outputs.run == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install software-properties-common
          sudo add-apt-repository -y ppa:ettusresearch/uhd
          sudo apt-get update
          sudo apt-get -y install build-essential cmake git xxd \
            devscripts fakeroot debhelper libfftw3-dev qtbase5-dev libopengl-dev libqt5opengl5-dev \
            qttools5-dev qttools5-dev-tools qtmultimedia5-dev libqt5multimedia5-plugins libqt5websockets5-dev \
            libqt5quick5 qtwebengine5-dev qtbase5-private-dev \
            qml-module-qtlocation qml-module-qtpositioning qml-module-qtquick-window2 qml-module-qtquick-dialogs \
            qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-layouts qml-module-qtgraphicaleffects \
            libqt5serialport5-dev qtdeclarative5-dev qtpositioning5-dev qtlocation5-dev \
            libqt5charts5-dev libqt5texttospeech5-dev libqt5gamepad5-dev libqt5svg5-dev libfaad-dev libflac-dev zlib1g-dev \
            libusb-1.0-0-dev libhidapi-dev libboost-all-dev libasound2-dev libopencv-dev libopencv-imgcodecs-dev \
            libxml2-dev bison flex ffmpeg  libpostproc-dev libavcodec-dev libavformat-dev \
            libopus-dev libcodec2-dev libairspy-dev libhackrf-dev \
            libbladerf-dev libsoapysdr-dev libiio-dev libuhd-dev libhamlib-dev libunwind-dev \
            libavahi-client-dev libavahi-common-dev libaio-dev \
            python3-mako python3-cheetah python3-numpy \
            autoconf automake libtool ninja-build
          bash cmake/ci/build_sdrplay.sh
      - name: Build SDRangel for Coverity
        if: steps.coverity_check.outputs.run == 'true'
        run: |
          ./.github/workflows/coverity.sh
