# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '26 4 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v4
      with:
          days-before-stale: 40
          days-before-close: 5       
          stale-issue-message: 'This issue is going to be closed due to inactivity'
          stale-pr-message: 'This PR is going to be closed due to inactivity'
          stale-issue-label: 'no-issue-activity'
          exempt-issue-labels: 'feature,enhancement,bug,documentation'
          exempt-all-assignees: true
          stale-pr-label: 'no-pr-activity'
